-- CreateTable
CREATE TABLE `Ppdb` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nama` VARCHAR(191) NOT NULL,
    `jk` VARCHAR(191) NOT NULL,
    `nik` VARCHAR(191) NOT NULL,
    `no_kk` VARCHAR(191) NOT NULL,
    `tempat_lahir` VARCHAR(191) NOT NULL,
    `tgl_lahir` VARCHAR(191) NOT NULL,
    `no_akte` VARCHAR(191) NOT NULL,
    `agama` VARCHAR(191) NOT NULL,
    `kewarganegaraan` VARCHAR(191) NOT NULL,
    `alamat` VARCHAR(191) NOT NULL,
    `tinggal_bersama` VARCHAR(191) NOT NULL,
    `anak_ke` VARCHAR(191) NOT NULL,
    `usia` VARCHAR(191) NOT NULL,
    `no_hp` VARCHAR(191) NOT NULL,
    `namaAyah` VARCHAR(191) NOT NULL,
    `nikAyah` VARCHAR(191) NOT NULL,
    `tahunLahirAyah` VARCHAR(191) NOT NULL,
    `pendidikanAyah` VARCHAR(191) NOT NULL,
    `pekerjaanAyah` VARCHAR(191) NOT NULL,
    `penghasilanAyah` VARCHAR(191) NOT NULL,
    `namaIbu` VARCHAR(191) NOT NULL,
    `nikIbu` VARCHAR(191) NOT NULL,
    `tahunLahirIbu` VARCHAR(191) NOT NULL,
    `pendidikanIbu` VARCHAR(191) NOT NULL,
    `pekerjaanIbu` VARCHAR(191) NOT NULL,
    `penghasilanIbu` VARCHAR(191) NOT NULL,
    `tinggiBadan` VARCHAR(191) NOT NULL,
    `beratBadan` VARCHAR(191) NOT NULL,
    `lingkarKepala` VARCHAR(191) NOT NULL,
    `jarakTempuh` VARCHAR(191) NOT NULL,
    `jumlahSaudara` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
